### ISSUE TITLE
/ is not a valid command name r(199)

### ISSUE THREAD

**Issue by claraberes** [steveofconnell/PanelCombine#1]
Dear Steve, 
Many thanks for creating this comment which would do exactly what I need. 
However, for now I am not able to make it work. 
After installation, when I run the example file "ExampleUse.do" I get the following error:
" / is not a valid command name
r(199);"
I ran on both Stata MP 15 and MP 16 on windows. 
Many thanks in advance for your help
Best regards 
Clara

**Comment by steveofconnell** [comment]
You have a basic error stemming from the first line of the program. change the `cd` command to a valid working directory for your windows system and it should work.

**Comment by steveofconnell** [comment]
the `cd` command that I used will work only on mac (my fault)

**Comment by claraberes** [comment]
Great, works fine! Thank you very much

**Comment by steveofconnell** [comment]
Sure! Glad to see someone using it. Its something I wrote quickly years ago, so might be buggy or not fully customized. But I am still using it in all my papers. If theres some feature you need, happy to collaborate on it.
